// Coverage gate for CI and `make coverage-mobile` (KAN-125).
//
//   dart run tool/coverage.dart helper
//       Writes test/coverage_helper_test.dart importing every lib/ file.
//       `flutter test --coverage` only reports files some test imports, so
//       without this an untested file silently drops out of the denominator
//       and the percentage overstates reality.
//
//   dart run tool/coverage.dart check --min <percent> [--min-file <percent>] [lcov.info]
//       Fails (exit 1) when total line coverage is below --min, or when any
//       single file is below --min-file, and lists the least-covered files.
//       The per-file floor stops one weak file hiding behind a high total.
import 'dart:io';

const _helperPath = 'test/coverage_helper_test.dart';
const _defaultLcov = 'coverage/lcov.info';

void main(List<String> args) {
  if (args.isEmpty) _usage();
  switch (args.first) {
    case 'helper':
      _writeHelper();
    case 'check':
      _check(args.skip(1).toList());
    default:
      _usage();
  }
}

Never _usage() {
  stderr.writeln(
    'usage: dart run tool/coverage.dart helper\n'
    '       dart run tool/coverage.dart check --min <percent> '
    '[--min-file <percent>] [lcov.info]',
  );
  exit(64);
}

void _writeHelper() {
  final libFiles =
      Directory('lib')
          .listSync(recursive: true)
          .whereType<File>()
          .map((file) => file.path.replaceAll(r'\', '/'))
          .where((path) => path.endsWith('.dart'))
          .toList()
        ..sort();
  final imports = [
    for (final (index, path) in libFiles.indexed)
      "import 'package:fitness_app/${path.substring('lib/'.length)}' as i$index;",
  ];
  File(_helperPath).writeAsStringSync(
    '// GENERATED by tool/coverage.dart — do not edit or commit.\n'
    '// ignore_for_file: unused_import, directives_ordering\n'
    '${imports.join('\n')}\n\n'
    'void main() {}\n',
  );
  // Keep the file format-clean so a local `make check-mobile` after a
  // coverage run doesn't trip the format gate on it.
  Process.runSync('dart', ['format', _helperPath], runInShell: true);
  stdout.writeln('Wrote $_helperPath (${libFiles.length} libraries).');
}

/// Removes `flag <percent>` from [args] and returns the percentage, or null
/// when the flag is absent and optional.
double? _takePercent(List<String> args, String flag, {required bool required}) {
  final index = args.indexOf(flag);
  if (index == -1) {
    if (required) _usage();
    return null;
  }
  if (index + 1 >= args.length) _usage();
  final value = double.tryParse(args[index + 1]);
  // NaN or out-of-range would make every comparison pass: fail closed.
  if (value == null || !value.isFinite || value < 0 || value > 100) {
    stderr.writeln('$flag must be a percentage between 0 and 100.');
    exit(64);
  }
  args.removeRange(index, index + 2);
  return value;
}

void _check(List<String> args) {
  final rest = [...args];
  final min = _takePercent(rest, '--min', required: true)!;
  final minFile = _takePercent(rest, '--min-file', required: false);
  final lcov = File(rest.isEmpty ? _defaultLcov : rest.first);
  if (!lcov.existsSync()) {
    stderr.writeln('No coverage report at ${lcov.path}.');
    exit(1);
  }

  final perFile = <String, (int hit, int found)>{};
  String? current;
  var found = 0;
  var hit = 0;
  for (final line in lcov.readAsLinesSync()) {
    if (line.startsWith('SF:')) {
      current = line.substring(3).replaceAll(r'\', '/');
      found = 0;
      hit = 0;
    } else if (line.startsWith('LF:')) {
      found = int.parse(line.substring(3));
    } else if (line.startsWith('LH:')) {
      hit = int.parse(line.substring(3));
    } else if (line == 'end_of_record' && current != null) {
      perFile[current] = (hit, found);
      current = null;
    }
  }

  final totalFound = perFile.values.fold(0, (sum, f) => sum + f.$2);
  final totalHit = perFile.values.fold(0, (sum, f) => sum + f.$1);
  final percent = totalFound == 0 ? 0.0 : 100 * totalHit / totalFound;

  final weakest = perFile.entries.where((entry) => entry.value.$2 > 0).toList()
    ..sort(
      (a, b) => (a.value.$1 / a.value.$2).compareTo(b.value.$1 / b.value.$2),
    );
  stdout.writeln('Least-covered files:');
  for (final entry in weakest.take(10)) {
    final (fileHit, fileFound) = entry.value;
    final filePercent = (100 * fileHit / fileFound).toStringAsFixed(1);
    stdout.writeln('  $filePercent%  ${entry.key} ($fileHit/$fileFound)');
  }
  stdout.writeln(
    'Total line coverage: ${percent.toStringAsFixed(2)}% '
    '($totalHit/$totalFound lines, ${perFile.length} files); '
    'floor ${min.toStringAsFixed(2)}%.',
  );
  final belowFileFloor = minFile == null
      ? const <MapEntry<String, (int, int)>>[]
      : weakest
            .where((entry) => 100 * entry.value.$1 / entry.value.$2 < minFile)
            .toList();
  if (minFile != null) {
    stdout.writeln('Per-file floor ${minFile.toStringAsFixed(2)}%.');
  }
  for (final entry in belowFileFloor) {
    final (fileHit, fileFound) = entry.value;
    stderr.writeln(
      'Below the per-file floor: ${entry.key} '
      '${(100 * fileHit / fileFound).toStringAsFixed(1)}% '
      '($fileHit/$fileFound)',
    );
  }
  if (percent < min) {
    stderr.writeln('Coverage is below the floor.');
    exit(1);
  }
  if (belowFileFloor.isNotEmpty) exit(1);
}
