// Coverage gate for CI and `make coverage-mobile` (KAN-125).
//
//   dart run tool/coverage.dart helper
//       Writes test/coverage_helper_test.dart importing every lib/ file.
//       `flutter test --coverage` only reports files some test imports, so
//       without this an untested file silently drops out of the denominator
//       and the percentage overstates reality.
//
//   dart run tool/coverage.dart check --min <percent> [lcov.info]
//       Fails (exit 1) when total line coverage is below the floor, and
//       lists the least-covered files.
import 'dart:io';

const _helperPath = 'test/coverage_helper_test.dart';
const _defaultLcov = 'coverage/lcov.info';

void main(List<String> args) {
  if (args.isEmpty) _usage();
  switch (args.first) {
    case 'helper':
      _writeHelper();
    case 'check':
      _check(args.skip(1).toList());
    default:
      _usage();
  }
}

Never _usage() {
  stderr.writeln(
    'usage: dart run tool/coverage.dart helper\n'
    '       dart run tool/coverage.dart check --min <percent> [lcov.info]',
  );
  exit(64);
}

void _writeHelper() {
  final libFiles =
      Directory('lib')
          .listSync(recursive: true)
          .whereType<File>()
          .map((file) => file.path.replaceAll(r'\', '/'))
          .where((path) => path.endsWith('.dart'))
          .toList()
        ..sort();
  final imports = [
    for (final (index, path) in libFiles.indexed)
      "import 'package:fitness_app/${path.substring('lib/'.length)}' as i$index;",
  ];
  File(_helperPath).writeAsStringSync(
    '// GENERATED by tool/coverage.dart — do not edit or commit.\n'
    '// ignore_for_file: unused_import, directives_ordering\n'
    '${imports.join('\n')}\n\n'
    'void main() {}\n',
  );
  // Keep the file format-clean so a local `make check-mobile` after a
  // coverage run doesn't trip the format gate on it.
  Process.runSync('dart', ['format', _helperPath], runInShell: true);
  stdout.writeln('Wrote $_helperPath (${libFiles.length} libraries).');
}

void _check(List<String> args) {
  final minIndex = args.indexOf('--min');
  if (minIndex == -1 || minIndex + 1 >= args.length) _usage();
  final min = double.tryParse(args[minIndex + 1]);
  // NaN or out-of-range would make every comparison pass: fail closed.
  if (min == null || !min.isFinite || min < 0 || min > 100) {
    stderr.writeln('--min must be a percentage between 0 and 100.');
    exit(64);
  }
  final rest = [...args]..removeRange(minIndex, minIndex + 2);
  final lcov = File(rest.isEmpty ? _defaultLcov : rest.first);
  if (!lcov.existsSync()) {
    stderr.writeln('No coverage report at ${lcov.path}.');
    exit(1);
  }

  final perFile = <String, (int hit, int found)>{};
  String? current;
  var found = 0;
  var hit = 0;
  for (final line in lcov.readAsLinesSync()) {
    if (line.startsWith('SF:')) {
      current = line.substring(3).replaceAll(r'\', '/');
      found = 0;
      hit = 0;
    } else if (line.startsWith('LF:')) {
      found = int.parse(line.substring(3));
    } else if (line.startsWith('LH:')) {
      hit = int.parse(line.substring(3));
    } else if (line == 'end_of_record' && current != null) {
      perFile[current] = (hit, found);
      current = null;
    }
  }

  final totalFound = perFile.values.fold(0, (sum, f) => sum + f.$2);
  final totalHit = perFile.values.fold(0, (sum, f) => sum + f.$1);
  final percent = totalFound == 0 ? 0.0 : 100 * totalHit / totalFound;

  final weakest = perFile.entries.where((entry) => entry.value.$2 > 0).toList()
    ..sort(
      (a, b) => (a.value.$1 / a.value.$2).compareTo(b.value.$1 / b.value.$2),
    );
  stdout.writeln('Least-covered files:');
  for (final entry in weakest.take(10)) {
    final (fileHit, fileFound) = entry.value;
    final filePercent = (100 * fileHit / fileFound).toStringAsFixed(1);
    stdout.writeln('  $filePercent%  ${entry.key} ($fileHit/$fileFound)');
  }
  stdout.writeln(
    'Total line coverage: ${percent.toStringAsFixed(2)}% '
    '($totalHit/$totalFound lines, ${perFile.length} files); '
    'floor ${min.toStringAsFixed(2)}%.',
  );
  if (percent < min) {
    stderr.writeln('Coverage is below the floor.');
    exit(1);
  }
}
