# Generated by Django 5.2.9 on 2026-07-03 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def blank_barcodes_to_null(apps, schema_editor):
    # A single row may carry '' from the pre-null era; under null=True two
    # blanks would collide on the unique constraint, NULLs never do.
    FoodItem = apps.get_model("foods", "FoodItem")
    FoodItem.objects.filter(barcode="").update(barcode=None)


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_single_food_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_foods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="source",
            field=models.CharField(
                choices=[("openfoodfacts", "Open Food Facts"), ("custom", "Custom")],
                default="openfoodfacts",
                max_length=32,
            ),
        ),
        migrations.RunPython(blank_barcodes_to_null, migrations.RunPython.noop),
    ]
