# Generated by Django 5.2.9 on 2026-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0006_fooditem_owner_alter_fooditem_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
