# Generated by Django 5.2.9 on 2026-07-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0008_fooditem_overrides_foodeditproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="community_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
