# Generated by Django 5.2.9 on 2026-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0009_fooditem_community_verified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("openfoodfacts", "Open Food Facts"),
                    ("custom", "Custom"),
                    ("fatsecret", "FatSecret"),
                ],
                default="openfoodfacts",
                max_length=32,
            ),
        ),
    ]
