# Generated by Django 5.2.9 on 2026-06-28 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0005_single_food_image"),
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mealentry",
            index=models.Index(
                fields=["user", "consumed_at"], name="meal_entry_user_time_idx"
            ),
        ),
    ]
