#!/usr/bin/env python3
"""Regenerate the CIQUAL raw-food protein reference table for the mobile app.

Produces apps/mobile/lib/features/nutrition/data/ciqual_raw_refs.dart from the
ANSES CIQUAL 2020 composition table (English edition): every food in group 04
("meat, egg and fish") whose name marks it as raw, keyed by the CIQUAL
`alim_code` that Open Food Facts exposes as `ecoscore_data.agribalyse` on
matched products. The app uses these values as the raw-reference denominator
for cooked-basis detection (see detectCookedNutritionBasis in
food_models.dart).

Usage:
    python3 scripts/generate_ciqual_raw_refs.py [path/to/CIQUAL_ENG.csv]

Without a path, the CSV is downloaded from the Open Food Facts mirror.
"""

from __future__ import annotations

import csv
import io
import sys
import urllib.request
from pathlib import Path

CSV_URL = (
    "https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/"
    "main/external-data/ciqual/ciqual/CIQUAL2020_ENG_2020_07_07.csv"
)
OUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "apps/mobile/lib/features/nutrition/data/ciqual_raw_refs.dart"
)

MEAT_EGG_FISH_GROUP = "04"
PROTEIN_COLUMNS = (
    "Protein (g/100g)",
    "Protein, crude, N x 6.25 (g/100g)",
)


def parse_value(raw: str) -> float | None:
    """CIQUAL numbers use decimal commas; '<x', 'traces', '-' and blanks are
    below-detection or missing markers, useless as a ratio denominator."""
    cleaned = raw.strip()
    if not cleaned or cleaned in {"-", "traces"} or cleaned.startswith("<"):
        return None
    try:
        return float(cleaned.replace(",", "."))
    except ValueError:
        return None


def load_rows(path: str | None) -> list[dict[str, str]]:
    if path:
        text = Path(path).read_text(encoding="utf-8-sig")
    else:
        print(f"Downloading {CSV_URL}", file=sys.stderr)
        with urllib.request.urlopen(CSV_URL) as response:
            text = response.read().decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text), delimiter="\t"))


def main() -> None:
    rows = load_rows(sys.argv[1] if len(sys.argv) > 1 else None)
    refs: dict[int, float] = {}
    for row in rows:
        if row["alim_grp_code"] != MEAT_EGG_FISH_GROUP:
            continue
        if ", raw" not in row["alim_nom_eng"].lower():
            continue
        protein = next(
            (v for col in PROTEIN_COLUMNS if (v := parse_value(row[col])) is not None),
            None,
        )
        if protein is None:
            continue
        refs[int(row["alim_code"])] = protein

    lines = [
        "// GENERATED by scripts/generate_ciqual_raw_refs.py — do not edit by hand.",
        "//",
        "// Protein per 100 g of the *raw* (uncooked) food for every CIQUAL 2020",
        '// entry in group 04 ("meat, egg and fish") whose name marks it as raw,',
        "// keyed by the CIQUAL `alim_code` that OFF exposes as",
        "// `ecoscore_data.agribalyse` on matched products. Raw muscle protein is",
        "// a stable reference: cooking concentrates it through water loss while",
        "// fat loss leaves it untouched, so a label far above the raw reference",
        "// means the cooked column was entered (see detectCookedNutritionBasis).",
        "",
        "/// Raw-food protein g/100g by CIQUAL food code (ANSES CIQUAL 2020).",
        "const Map<int, double> ciqualRawProteinG100g = {",
    ]
    for code in sorted(refs):
        lines.append(f"  {code}: {refs[code]},")
    lines.append("};")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(refs)} entries to {OUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
