# Generated by Django 5.2.9 on 2026-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="nutrient_goals",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
