# Generated by Django 5.2.9 on 2026-07-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0003_userpreferences_focus_nutrients"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="warn_nutrients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
