# Generated by Django 5.2.9 on 2026-06-08 17:46

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def assert_no_ci_duplicate_emails(apps, schema_editor):
    """Guard the case-insensitive unique email constraint against bad data.

    Before this migration the only DB-level guarantee was a case-sensitive
    ``unique=True`` on ``email``, so case-variant duplicates (e.g. John@x.com
    and john@x.com) could already exist. Adding ``uniq_email_ci`` over such
    rows fails with an opaque IntegrityError; surface an actionable error
    instead. Resolution (merge/remove the offending accounts) is intentionally
    left manual since email is the login identity.
    """
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    conflicts = [
        row["email_ci"]
        for row in (
            User.objects.using(db_alias)
            .values(email_ci=Lower("email"))
            .annotate(n=Count("id"))
            .filter(n__gt=1)
            .order_by("email_ci")
        )
    ]
    if conflicts:
        raise RuntimeError(
            "Cannot add case-insensitive unique email constraint (uniq_email_ci): "
            "existing rows have case-variant duplicate emails: "
            f"{', '.join(conflicts)}. "
            "Resolve these duplicates (merge or remove accounts) before migrating."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_emailverificationtoken"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            assert_no_ci_duplicate_emails,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="uniq_email_ci"
            ),
        ),
    ]
