# Generated by Django 5.2.9 on 2026-07-18 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_accountdeletiontoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_policy_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.CreateModel(
            name="PolicyAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_version", models.CharField(max_length=32)),
                ("accepted_at", models.DateTimeField()),
                ("health_consent_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "policy_version"),
                        name="uniq_policy_acceptance_per_version",
                    )
                ],
            },
        ),
    ]
